### ISSUE TITLE
concatenate -> mir.ndslice.concatenation: concatenation

### ISSUE THREAD

**Issue by 9il** [ShigekiKarita/numir#2]
[`mir.ndslice.concatenation: concatenation`](http://docs.algorithm.dlang.io/latest/mir_ndslice_concatenation.html#.concatenation) was added today. `concatenation` creates a lazy `Concatenation` view. `mir.ndslice.allocation: slice` can be used to allocate new ndslice with data from `Concatenation`. `concatenate` can be expressed as combination `concatenation!axis(slices).slice`

Thank you for using Mir!

**Comment by ShigekiKarita** [comment]
Wow, this should be really what I want. I agree with you to rewrite `concatenate`.

Thanks for developing Mir!

**Comment by ShigekiKarita** [comment]
done with a numpy-like negative axis support https://github.com/ShigekiKarita/numir/commit/13445128b2be751f66f38c00041c3bdaa5d7ac51
